### ISSUE TITLE
Student and tutor portal UI upgrade

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#2]
We are improving the UI for the portal to better handle future expansion with new features.

**Comment by garry-traynor** [comment]
I'd love to get some previews of the new UI when available.

**Comment by jameshandsaker** [comment]
Something that would also be really great is if either at a course or organisation level you could change the accessible features for students and tutors. So for example turning off access to results as we don't have any accredited courses.

**Comment by ari** [comment]
Good point. I think in many cases this could automatically adjust the UI. Show documents, results, assessments, etc only when there is content in those places. In other places, we would want options: do you want tutors to mark the roll?

**Comment by JamesWEA** [comment]
Hi Ari, following on from the email I sent you about this, I asked our tutors what they want to change or add for the portal. We don't really use the portal with our students except for feedback submission so most of our changes are for tutors and us.

**Portal Changes (Tutor requests):**
- Stop displaying old courses on dashboard, either for feedback as students or marking the roll
- Sort or display Class Roll / Resources A-Z
- Ability to email whole class a simple message through portal - other requests have been asking for ability to send documents as well
- Ability to download a PDF copy of the class roll through portal (some tutors still like to mark it on paper then mark the roll online after the class is over)
- Some tutors have multiple classes in a day, so being able to see all classes they are teaching and/or attending on the dashboard on the day when they login instead of the earliest one.

**Portal Changes (Admin requests):**
- Fix display formatting (e.g. italics / bold) for markup for the course details
- Being able to login "as the tutor" to view what the tutor is seeing on their end for technical issues.
- Fix the "blank login" cache issue (if possible)
- Please add paragraph spacing in the comments box for course approval
- Tutors being able to see what special needs the student has in real time (current task open)
- Tutors being able to see feedback comments students have submitted (WIP from what I remember?)
- Alter the feedback page so students know that the comments box is optional, and perhaps add in a tickbox that they can tick if they do want us to display what they say in the testimonials section. We keep getting students asking us if their names will be anonymous when submitting feedback, so perhaps changing that message already there to something more direct would be better to reassure students that the tutor won't know who the feedback is from.
- ${subscriptions} should go directly to mailing lists not waiting lists.

Also the chance to see the new interface would be good too, would it be ok to get the tutors to look at it as well since they have to see it more than we do?

James

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/student-and-tutor-portal-ui-upgrade/179
