### ISSUE TITLE
Assessment submissions in portal

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourse-roadmap#9]
A mechanism for students to upload assessments through the portal.

**Comment by garry-traynor** [comment]
Would have great relevance for larger RTO's with higher order quals. Good feature

**Comment by dnunn-hse** [comment]
This will be very beneficial, particularly with remote learning due to Covid19. I'd be interested to understand if this a document upload or whether or not there will be the option to conduct other types assessments via this feature. Also interested to know if marking and feedback can be provided to the student via this feature. Will there be a file upload limit? We would really like the ability to upload photo/video evidence which would be saved and linked to student profiles etc.
A great step in a forward direction for onCourse.

**Comment by ari** [comment]
Our plan is to make this quite simple. We don't want to stray too far into building an LMS and there are some terrific choices for assessment marking like CloudAssess with which integration is easy.

Right now we are thinking our implementation is a OneDrive/DropBox/GoogleDrive integration. Students can upload forms, docs, photos, video, etc.

If you want a full course delivery tool, SCORM, marking rubrics, etc then a dedicated tool is probably best. However we want to fill a gap here for simple capture of evidence.

**Comment by simonestockl** [comment]
Moved to https://oncourse.discourse.group/t/assessment-submissions-in-portal/199
